export * from './aluno-controller'
export * from './cadeira-controller'
export * from './cadeiras-alunos-controller'
export * from './load-cadeira-controller'
export * from './professor-controller'
export * from './update-cadeiras-alunos-controller'
