export * from './aluno-controller-factory'
export * from './cadeira-controller-factory'
export * from './cadeiras-alunos-controller-factory'
export * from './load-cadeiras-controller-factory'
export * from './professor-controller-factory'
export * from './update-cadeiras-alunos-factory'
