export * from './aluno-validation-factory'
export * from './cadeira-validation-factory'
export * from './cadeiras-alunos-validation-factory'
export * from './professor-validation-factory'
export * from './update-cadeiras-alunos-validation-factory'
