export * from './helpers/prisma-helper'
export * from './aluno-prisma-repository'
export * from './cadeira-prisma-repository'
export * from './log-prisma-repository'
export * from './professor-prisma-repository'
export * from './cadeiras-alunos-prisma-repository'
