export * from './add-aluno'
export * from './add-cadeira'
export * from './add-cadeiras-alunos'
export * from './add-professor'
export * from './check-professor-by-id'
export * from './check-aluno-by-id'
export * from './check-cadeira-by-id'
export * from './check-cadeira-by-period'
